- name: Packages

  hosts: all
  remote_user: agent
  become: true

  handlers:
    - name: Reboot
      ansible.builtin.reboot:

  tasks:

    - name: Add repo with podman 4
      ansible.builtin.script: 
        cmd: podman_4_ubuntu_repo.sh
        creates: /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg

    - name: Update packages
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: true
    
    - name: Install packages
      ansible.builtin.apt:
        name:
          - podman
          - netavark
          - aardvark-dns
          - unattended-upgrades
        state: present
      notify: Reboot
