- name: Firewall

  hosts: all
  remote_user: agent
  become: true

  tasks:
    - name: Allow access to port SSH/22
      community.general.ufw:
        rule: allow 
        port: ssh

    - name: Enable UFW
      community.general.ufw:
        default: deny
        state: enabled
